environment: "prod"

paths:
  input_text: "prod/text.txt"
  encrypted_text: "prod/encrypted_text.txt"
  encrypted_key: "prod/encrypted_key.txt"
  public_key: "prod/public_key.txt"
  private_key: "prod/private_key.txt"
  decrypted_text: "prod/decrypted_text.txt"

debug:
  enabled: false
  verbose: false